In [1]:
%pip install leia-br

Collecting leia-br
  Using cached leia_br-0.0.1-py2.py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: requests in /home/bradachi/Documentos/gitpath/internet-of-reviews/ior/lib/python3.12/site-packages (from leia-br) (2.33.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/bradachi/Documentos/gitpath/internet-of-reviews/ior/lib/python3.12/site-packages (from requests->leia-br) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /home/bradachi/Documentos/gitpath/internet-of-reviews/ior/lib/python3.12/site-packages (from requests->leia-br) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in /home/bradachi/Documentos/gitpath/internet-of-reviews/ior/lib/python3.12/site-packages (from requests->leia-br) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in /home/bradachi/Documentos/gitpath/internet-of-reviews/ior/lib/python3.12/site-packages (from requests->leia-br) (2026.4.22)
Using cached leia_br-0.0.1-py2.py3-none-any.whl (130 kB)
Installing collected packages: leia-br
Successfully installed leia-br-0.0.1
Note: you may need to restart the kernel to use updated packages.

In [3]:
# Imports
#  /home/bradachi/Documentos/GitHub/NLP_teste/NLP_ENV/bin/python -m pip install 
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
import string
from textblob import TextBlob
from LeIA import SentimentIntensityAnalyzer
#import requests
#import json
#import pprint
#import lxml
#import time
#from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator
#import matplotlib.pyplot as plt 
# from bertopic import BERTopic
#from PIL import Image
#import numpy as np
#from statsmodels.distributions.empirical_distribution import ECDF
#import matplotlib.ticker as mtick
# from selenium import webdriver
# from webdriver_manager.firefox import GeckoDriverManager 
# from selenium.webdriver.firefox.service import Service 
# from selenium.webdriver.common.action_chains import ActionChains
# from selenium.webdriver.common.keys import Keys
# from selenium.common.exceptions import NoSuchElementException

[nltk_data] Downloading package punkt to /home/bradachi/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/bradachi/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/bradachi/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [13]:
produtos = pd.read_csv("../data/general_products/produtos.csv")
produtos

,id,date_created,catalog_product_id,domain_id,name,main_features,quality_type,priority,type,keywords,description
0,MLB46241561,2025-02-21T13:14:52Z,MLB46241561,MLB-REFRIGERATOR_AND_FREEZER_SENSORS,Sensores Temperatura/evaporador Split Electrol...,[],COMPLETE,MEDIUM,PRODUCT,Sensores Temperatura/evaporador Split Electrol...,NaN
1,MLB39940858,2024-08-27T21:56:42Z,MLB39940858,MLB-REFRIGERATOR_AND_FREEZER_SENSORS,2 Sensores De Temperatura Refrigerador Crd36,[],COMPLETE,MEDIUM,PRODUCT,2 Sensores De Temperatura Refrigerador Crd36,NaN
2,MLB48776606,2025-04-19T02:23:06Z,MLB48776606,MLB-REFRIGERATOR_AND_FREEZER_SENSORS,Termofusivel 105c + 2 Sensores Temperatura Degelo,[],PRIMITIVE,MEDIUM,PRODUCT,Termofusivel 105c + 2 Sensores Temperatura Degelo,NaN
3,MLB59018447,2025-10-05T02:13:07Z,MLB59018447,MLB-REFRIGERATOR_AND_FREEZER_SENSORS,Kit 2 Sensores 5k Geladeira Electrolux,[],COMPLETE,MEDIUM,PRODUCT,Kit 2 Sensores 5k Geladeira Electrolux,NaN
4,MLB44743999,2024-12-13T15:48:20Z,MLB44743999,MLB-REFRIGERATOR_AND_FREEZER_SENSORS,Termostato Bimetal +sensores Temp. P/ Cervejei...,[],COMPLETE,MEDIUM,PRODUCT,Termostato Bimetal +sensores Temp. P/ Cervejei...,NaN
...,...,...,...,...,...,...,...,...,...,...,...
23039,MLB38765729,2024-07-31T01:39:07Z,MLB38765729,MLB-DIMMERS,Interruptor inteligente Wi-Fi para ventilador ...,[],COMPLETE,MEDIUM,PRODUCT,Interruptor inteligente Wi-Fi para ventilador ...,NaN
23040,MLB45805005,2025-01-30T19:51:00Z,MLB45805005,MLB-DIMMERS,Interruptor Inteligente Zigbee Novadigital 2 T...,[],COMPLETE,MEDIUM,PRODUCT,Interruptor Inteligente Zigbee Novadigital 2 T...,NaN
23041,MLB47688342,2025-04-04T17:32:34Z,MLB47688342,MLB-DIMMERS,Interruptor Inteligente Zigbee Novadigital 1 T...,[],COMPLETE,MEDIUM,PRODUCT,Interruptor Inteligente Zigbee Novadigital 1 T...,NaN
23042,MLB39454456,2024-08-22T19:56:27Z,MLB39454456,MLB-DIMMERS,Interruptor Inteligente Wi-fi Com Função Dimme...,[],COMPLETE,MEDIUM,PRODUCT,Interruptor Inteligente Wi-fi Com Função Dimme...,NaN
23043,MLB44773654,2024-12-14T01:35:19Z,MLB44773654,MLB-DIMMERS,Interruptor Inteligente Zigbee 4x4 4 Teclas Fí...,[],COMPLETE,MEDIUM,PRODUCT,Interruptor Inteligente Zigbee 4x4 4 Teclas Fí...,NaN

In [14]:
avaliacoes = pd.read_csv("../data/general_products/avaliacoes.csv")
avaliacoes

,texto,nota,id,data
0,Excelente produto!!.,5,MLB46241561,09 out. 2025
1,Muito bom.,5,MLB48090512,15 out. 2025
2,Muito bom produto.,5,MLB48090512,16 out. 2025
3,Produto bom. Sem retorno.,5,MLB48090512,20 nov. 2025
4,Produto confiável e original. Eu mesmo arrumei...,5,MLB29176649,27 out. 2025
...,...,...,...,...
9648,Atendeu super bem para controles de ventilador...,5,MLB50911897,28 nov. 2025
9649,Produto excelente e facil instalacao.,5,MLB50911897,01 dez. 2025
9650,"Simples, rápido e eficiente. Produto muito bom...",5,MLB50911897,25 out. 2025
9651,É elogiado por sua facilidade de configuração ...,5,MLB50911897,20 nov. 2025
9652,O produto cumpre o que promete possui um bom a...,5,MLB50911897,16 out. 2025

In [15]:
perguntas = pd.read_csv("../data/general_products/perguntas.csv")
perguntas

,pergunta,resposta,id,data
0,Minha cervejeira é VN28AF Termostato sollatek ...,"Boa tarde, seu termostato saiu de linha o subs...",MLB44743999,27/11/2025
1,Esse termostato tem os 4 pinos?,"Boa tarde, são 6 pinos porem os que tem função...",MLB44743999,26/11/2025
2,Teria para o modelo VF56DB 220V,"Boa tarde, seu modelo usa termostato sollatek,...",MLB44743999,26/06/2025
3,Ok ele e 220v,O termostato do anúncio é bivolt.,MLB44743999,15/05/2025
4,Bom dia ele serve para o modelo vb15 metal frio,"Bom dia, sim temos programações para expositor...",MLB44743999,16/05/2025
...,...,...,...,...
28994,Olá é luz quente,"Olá Tudo bem? Não, a luz é branco neutro 4000k...",MLB46936892,02/09/2025
28995,Precisso da nota fiscal de este produto,Olá boa tarde! Tudo bem? Claro! Pode nos envia...,MLB46936892,23/06/2025
28996,"Muito obrigado pela atenção, E27 que preciso. ...",Deu certo o Sr. conseguiu utilizar?,MLB46936892,29/05/2025
28997,Comprei chegou mas a rosca não é E27 é menor,Boa noite! Tudo bem? Mas esse modelo não temos...,MLB46936892,28/05/2025
28998,tem branco quente?,Olá boa tarde! Tudo bem? Infelizmente não temo...,MLB46936892,12/05/2025

In [16]:
contextos = pd.read_csv("../data/general_products/contexto.csv")
contextos

,Context_Id,Context,value_id,value_name,id
0,BRAND,Marca,188.0,Electrolux,MLB46241561
1,MODEL,Modelo,47713338.0,YI09F YI09R YI12F YI12R,MLB46241561
2,SENSOR_TYPE,Tipo de sensor,39861884.0,Temperatura,MLB46241561
3,WEIGHT,Peso,19173692.0,0.2 g,MLB46241561
4,BRAND,Marca,17452295.0,GBMak,MLB39940858
...,...,...,...,...,...
299579,IS_PROGRAMMABLE,É programável,242085.0,Sim,MLB44773654
299580,WITH_WI_FI,Com Wi-Fi,242084.0,Não,MLB44773654
299581,ANATEL_HOMOLOGATION_NUMBER,Homologação Anatel Nº,39981355.0,104162111765,MLB44773654
299582,MANUFACTURER,Fabricante,2449062.0,Novadigital,MLB44773654
299583,ALPHANUMERIC_MODELS,Modelo alfanumérico,NaN,NTZB-04-B,MLB44773654

In [17]:
wifiObjects = contextos[contextos["Context_Id"] == "WITH_WI_FI"]
wifiObjects2 = contextos[contextos["Context_Id"] == "WITH_WI_FI_CONNECTION"]
wifiObjects3 = contextos[contextos["Context_Id"] == "IS_COMPATIBLE_WITH_WI_FI_MODULE"]
wifiObjects4 = contextos[contextos["Context_Id"] == "WITH_WIFI"]
bltObjects = contextos[contextos["Context_Id"] == "WITH_BLUETOOTH"]
mobNet = contextos[contextos["Context_Id"] == "WITH_MOBILE_NETWORK"]
nfc = contextos[contextos["Context_Id"] == "WITH_NFC"]
wl = contextos[contextos["Context_Id"] == "IS_WIRELESS"]

mobConn = contextos[contextos["Context_Id"] == "MOBILE_CONNECTIONS"]
connTypesObjects = contextos[contextos["Context_Id"] == "CONNECTION_TYPES"]
wireless = contextos[contextos["Context_Id"] == "WIRELESS_STANDARDS"]
connObjects = contextos[contextos["Context_Id"] == "CONNECTIVITY"]
mobNetType = contextos[contextos["Context_Id"] == "MOBILE_NETWORK"]
comp1 = contextos[contextos["Context_Id"] == "COMPATIBLE_VIRTUAL_ASSISTANTS"]
comp2 = contextos[contextos["Context_Id"] == "COMPATIBLE_SMART_APPS"]


smartObjectsID = pd.concat([wifiObjects, wifiObjects2, 
                            wifiObjects3, wifiObjects4, 
                            bltObjects, mobNet, nfc, wl])

smartObjectsID = smartObjectsID[smartObjectsID["value_name"] == "Sim"]

smartObjectsID = pd.concat([smartObjectsID, connTypesObjects, 
                            connObjects, wireless, mobNetType,
                            comp1, comp2, mobConn])

smartObjectsID = smartObjectsID["id"].drop_duplicates().reset_index(drop=True)
smartObjectsID = list(smartObjectsID)
smartObjectsID

['MLB36333923',
 'MLB36139109',
 'MLB21345002',
 'MLB38703841',
 'MLB36398531',
 'MLB54448099',
 'MLB48677687',
 'MLB19552926',
 'MLB27839322',
 'MLB28002506',
 'MLB56994543',
 'MLB29568434',
 'MLB26446377',
 'MLB38750127',
 'MLB54236783',
 'MLB41626835',
 'MLB24455199',
 'MLB57356995',
 'MLB27985244',
 'MLB28682642',
 'MLB43616708',
 'MLB27769043',
 'MLB34345595',
 'MLB28754492',
 'MLB61666608',
 'MLB40002972',
 'MLB25735509',
 'MLB41799760',
 'MLB39171159',
 'MLB28037061',
 'MLB28834431',
 'MLB51925280',
 'MLB35985980',
 'MLB23222747',
 'MLB45867674',
 'MLB36956947',
 'MLB27238649',
 'MLB20049271',
 'MLB20545758',
 'MLB29417181',
 'MLB26085789',
 'MLB42639627',
 'MLB39983380',
 'MLB20662835',
 'MLB26051587',
 'MLB52139663',
 'MLB22145672',
 'MLB24198079',
 'MLB37791461',
 'MLB24228530',
 'MLB58376900',
 'MLB36411103',
 'MLB36034704',
 'MLB23942605',
 'MLB44845954',
 'MLB22031377',
 'MLB40543976',
 'MLB48710929',
 'MLB60176792',
 'MLB48848053',
 'MLB38347793',
 'MLB38264333',
 'MLB38532151',
 'MLB47457839',
 'MLB36860729',
 'MLB46028773',
 'MLB62124393',
 'MLB36440860',
 'MLB60004306',
 'MLB38607495',
 'MLB32041012',
 'MLB47385600',
 'MLB23494147',
 'MLB35472889',
 'MLB46164967',
 'MLB53366520',
 'MLB60025940',
 'MLB36389764',
 'MLB44846545',
 'MLB49322713',
 'MLB48199444',
 'MLB38182044',
 'MLB38530575',
 'MLB41961651',
 'MLB48058975',
 'MLB42137736',
 'MLB62221449',
 'MLB19714192',
 'MLB36205181',
 'MLB38887046',
 'MLB38580551',
 'MLB38652768',
 'MLB54497851',
 'MLB62190038',
 'MLB34233483',
 'MLB21307953',
 'MLB34064383',
 'MLB27714646',
 'MLB52688976',
 'MLB27186156',
 'MLB27392034',
 'MLB45247937',
 'MLB45132930',
 'MLB54439058',
 'MLB44770764',
 'MLB35846739',
 'MLB29340153',
 'MLB27275775',
 'MLB37704330',
 'MLB32392708',
 'MLB59687181',
 'MLB48535063',
 'MLB27552956',
 'MLB27826637',
 'MLB36143189',
 'MLB27816336',
 'MLB35241852',
 'MLB48212136',
 'MLB27108448',
 'MLB27090138',
 'MLB28688113',
 'MLB27857072',
 'MLB38423832',
 'MLB27108443',
 'MLB53547771',
 'MLB48418106',
 'MLB27352689',
 'MLB29262471',
 'MLB27222208',
 'MLB53757234',
 'MLB32645827',
 'MLB49363451',
 'MLB56483970',
 'MLB37079958',
 'MLB32309751',
 'MLB30942930',
 'MLB41156271',
 'MLB53348803',
 'MLB51916135',
 'MLB43438722',
 'MLB37231735',
 'MLB39899873',
 'MLB25389787',
 'MLB35792356',
 'MLB41177972',
 'MLB22775619',
 'MLB23206980',
 'MLB35434187',
 'MLB36257977',
 'MLB22802101',
 'MLB30483204',
 'MLB35675293',
 'MLB51294025',
 'MLB39899797',
 'MLB45439378',
 'MLB35781221',
 'MLB43289017',
 'MLB40602817',
 'MLB43970026',
 'MLB43956120',
 'MLB44591328',
 'MLB39707800',
 'MLB43349165',
 'MLB39154577',
 'MLB39970161',
 'MLB39484104',
 'MLB35936163',
 'MLB42885512',
 'MLB23206976',
 'MLB41562018',
 'MLB40274435',
 'MLB39898295',
 'MLB40053974',
 'MLB40486157',
 'MLB39914799',
 'MLB35795312',
 'MLB35681195',
 'MLB44164357',
 'MLB43293735',
 'MLB42363143',
 'MLB39484073',
 'MLB39967816',
 'MLB39977911',
 'MLB35939583',
 'MLB42949971',
 'MLB41413438',
 'MLB23050459',
 'MLB44592394',
 'MLB33851627',
 'MLB35766321',
 'MLB39686071',
 'MLB44914235',
 'MLB39484456',
 'MLB46840442',
 'MLB25133898',
 'MLB35683185',
 'MLB27271165',
 'MLB22889809',
 'MLB22969726',
 'MLB59128214',
 'MLB59142103',
 'MLB26871392',
 'MLB39993358',
 'MLB25420291',
 'MLB35438365',
 'MLB23584161',
 'MLB59133353',
 'MLB41543740',
 'MLB29377673',
 'MLB35791795',
 'MLB35807211',
 'MLB35732391',
 'MLB36031994',
 'MLB26871336',
 'MLB59131720',
 'MLB24889788',
 'MLB22611731',
 'MLB34349486',
 'MLB22490095',
 'MLB24272639',
 'MLB29793904',
 'MLB28577248',
 'MLB37231981',
 'MLB42110824',
 'MLB26720266',
 'MLB34112780',
 'MLB59173695',
 'MLB23061216',
 'MLB49673498',
 'MLB37386277',
 'MLB44411534',
 'MLB58422238',
 'MLB25766191',
 'MLB22761042',
 'MLB46189709',
 'MLB27860038',
 'MLB34090345',
 'MLB27731746',
 'MLB23013870',
 'MLB23123808',
 'MLB32101252',
 'MLB42947569',
 'MLB22511089',
 'MLB61750715',
 'MLB22663877',
 'MLB24080500',
 'MLB37847327',
 'MLB37940759',
 'MLB33953830',
 'MLB25133273',
 'MLB22695974',
 'MLB27463021',
 'MLB25132713',
 'MLB23967456',
 'MLB52833401',
 'MLB45307178',
 'MLB53785840',
 'MLB41592496',
 'MLB22948663',
 'MLB22937488',
 'MLB46469618',
 'MLB23967462',
 'MLB59017217',
 'MLB30987129',
 'MLB51035513',
 'MLB23017518',
 'MLB27789422',
 'MLB23546136',
 'MLB33324902',
 'MLB29664922',
 'MLB25132232',
 'MLB34015194',
 'MLB24517649',
 'MLB22266345',
 'MLB25254763',
 'MLB36521938',
 'MLB24764653',
 'MLB32966982',
 'MLB41773299',
 'MLB23008208',
 'MLB23066125',
 'MLB48175377',
 'MLB54037570',
 'MLB45225132',
 'MLB22621146',
 'MLB30405525',
 'MLB25132709',
 'MLB42478187',
 'MLB22652937',
 'MLB23802064',
 'MLB24155440',
 'MLB32166497',
 'MLB27794004',
 'MLB22511210',
 'MLB22969705',
 'MLB22663880',
 'MLB27861621',
 'MLB43331566',
 'MLB23483712',
 'MLB27775752',
 'MLB22663887',
 'MLB26753386',
 'MLB22775662',
 'MLB29160420',
 'MLB44993873',
 'MLB59099585',
 'MLB44895662',
 'MLB29103826',
 'MLB26890061',
 'MLB55667052',
 'MLB42340194',
 'MLB24141002',
 'MLB22737094',
 'MLB22723564',
 'MLB22490083',
 'MLB22511212',
 'MLB57509888',
 'MLB29329227',
 'MLB39099692',
 'MLB28995159',
 'MLB23791279',
 'MLB22695975',
 'MLB22642626',
 'MLB29241465',
 'MLB29605163',
 'MLB39552201',
 'MLB56136307',
 'MLB57583331',
 'MLB23558321',
 'MLB47041820',
 'MLB23491995',
 'MLB39136702',
 'MLB43173537',
 'MLB39012030',
 'MLB37193095',
 'MLB56722450',
 'MLB40167873',
 'MLB22837726',
 'MLB35733494',
 'MLB25254603',
 'MLB56951164',
 'MLB36961829',
 'MLB48873836',
 'MLB23677291',
 'MLB41949178',
 'MLB50750469',
 'MLB49860884',
 'MLB39060468',
 'MLB47354665',
 'MLB37837157',
 'MLB43487661',
 'MLB48863277',
 'MLB52339226',
 'MLB37257397',
 'MLB48828158',
 'MLB27727909',
 'MLB49777191',
 'MLB36328550',
 'MLB46493688',
 'MLB48549721',
 'MLB39373683',
 'MLB47949397',
 'MLB32382704',
 'MLB48499238',
 'MLB27736969',
 'MLB23808449',
 'MLB41922583',
 'MLB48523160',
 'MLB53784442',
 'MLB38259713',
 'MLB46405128',
 'MLB48862301',
 'MLB50501461',
 'MLB38148092',
 'MLB35477326',
 'MLB60358348',
 'MLB44897566',
 'MLB34235844',
 'MLB45233765',
 'MLB37839021',
 'MLB44011499',
 'MLB36520489',
 'MLB38605618',
 'MLB60214512',
 'MLB61406743',
 'MLB55541609',
 'MLB28903173',
 'MLB48816455',
 'MLB33058393',
 'MLB60723803',
 'MLB40835938',
 'MLB48839982',
 'MLB26109358',
 'MLB19710232',
 'MLB34019903',
 'MLB24151143',
 'MLB29338457',
 'MLB47722710',
 'MLB22881783',
 'MLB23763180',
 'MLB23763119',
 'MLB45948244',
 'MLB45673266',
 'MLB34372642',
 'MLB45809971',
 'MLB42598978',
 'MLB22538355',
 'MLB21145178',
 'MLB23427529',
 'MLB26378343',
 'MLB50871740',
 'MLB21337390',
 'MLB19756581',
 'MLB20005141',
 'MLB28698435',
 'MLB22856639',
 'MLB24804063',
 'MLB26378230',
 'MLB21294047',
 'MLB21558707',
 'MLB34265370',
 'MLB25947151',
 'MLB49826274',
 'MLB44982092',
 'MLB40872140',
 'MLB47719836',
 'MLB26833799',
 'MLB39137726',
 'MLB24253851',
 'MLB34223388',
 'MLB27094730',
 'MLB35955259',
 'MLB26969469',
 'MLB25578380',
 'MLB19712585',
 'MLB24716223',
 'MLB22906089',
 'MLB34140626',
 'MLB21788043',
 'MLB26136006',
 'MLB24113974',
 'MLB23912654',
 'MLB61692808',
 'MLB25124238',
 'MLB24455694',
 'MLB36217437',
 'MLB21720421',
 'MLB33068830',
 'MLB22892599',
 'MLB26197089',
 'MLB26515255',
 'MLB29562367',
 'MLB35099731',
 'MLB26197091',
 'MLB21692060',
 'MLB21915289',
 'MLB22811053',
 'MLB37901877',
 'MLB34226424',
 'MLB19606370',
 'MLB25482102',
 'MLB25391995',
 'MLB20466345',
 'MLB23343912',
 'MLB21492038',
 'MLB25952240',
 'MLB25952253',
 'MLB21558714',
 'MLB21835849',
 'MLB51690865',
 'MLB60069506',
 'MLB25952326',
 'MLB21024578',
 'MLB25952304',
 'MLB47725936',
 'MLB20466414',
 'MLB22305343',
 'MLB24588422',
 'MLB36212454',
 'MLB26378271',
 'MLB21340536',
 'MLB54054526',
 'MLB33035084',
 'MLB21305484',
 'MLB30607722',
 'MLB24658989',
 'MLB22828005',
 'MLB23609972',
 'MLB22958324',
 'MLB25392005',
 'MLB20656450',
 'MLB25578372',
 'MLB39259069',
 'MLB22752934',
 'MLB44200116',
 'MLB25778606',
 'MLB24608637',
 'MLB21847224',
 'MLB24658987',
 'MLB30210386',
 'MLB53179392',
 'MLB42012409',
 'MLB28865167',
 'MLB27735313',
 'MLB27719895',
 'MLB48551326',
 'MLB28482875',
 'MLB42012430',
 'MLB59597077',
 'MLB38331556',
 'MLB35845608',
 'MLB50743901',
 'MLB20537521',
 'MLB42088380',
 'MLB28534205',
 'MLB27275433',
 'MLB28799580',
 'MLB38543311',
 'MLB55015137',
 'MLB56749080',
 'MLB44633552',
 'MLB36399376',
 'MLB27541774',
 'MLB52111569',
 'MLB41952921',
 'MLB52863501',
 'MLB62254106',
 'MLB28485496',
 'MLB20537516',
 'MLB52833376',
 'MLB41991354',
 'MLB27940330',
 'MLB33975716',
 'MLB36881566',
 'MLB15458050',
 'MLB40459880',
 'MLB27733487',
 'MLB20537515',
 'MLB25212620',
 'MLB36192207',
 'MLB27736853',
 'MLB49548155',
 'MLB20484201',
 'MLB32961480',
 'MLB62239502',
 'MLB38741525',
 'MLB28373932',
 'MLB28255295',
 'MLB23255350',
 'MLB60017513',
 'MLB37237433',
 'MLB27859843',
 'MLB25212629',
 'MLB48874958',
 'MLB59777085',
 'MLB59985416',
 'MLB15469699',
 'MLB30770355',
 'MLB30393633',
 'MLB42144224',
 'MLB30096994',
 'MLB43104744',
 'MLB27699998',
 'MLB21485117',
 'MLB25824897',
 'MLB50969230',
 'MLB20537511',
 'MLB48222869',
 'MLB48459699',
 'MLB28500550',
 'MLB21346273',
 'MLB48000325',
 'MLB60012929',
 'MLB27472599',
 'MLB27547445',
 'MLB29339841',
 'MLB36852317',
 'MLB28525716',
 'MLB49886419',
 'MLB49908715',
 'MLB49918229',
 'MLB41238009',
 'MLB20517334',
 'MLB32390745',
 'MLB47944605',
 'MLB59470423',
 'MLB26837986',
 'MLB61320315',
 'MLB54822328',
 'MLB28534224',
 'MLB28512166',
 'MLB38572679',
 'MLB28836777',
 'MLB25212628',
 'MLB29057809',
 'MLB27738417',
 'MLB28473036',
 'MLB23972473',
 'MLB52137054',
 'MLB47973704',
 'MLB52854556',
 'MLB41233866',
 'MLB26316885',
 'MLB28538938',
 'MLB20537517',
 'MLB28800423',
 'MLB40698782',
 'MLB28374112',
 'MLB61741034',
 'MLB61427328',
 'MLB41981329',
 'MLB48962228',
 'MLB23077226',
 'MLB54429846',
 'MLB28476428',
 'MLB49928876',
 'MLB27975906',
 'MLB28373831',
 'MLB23480981',
 'MLB22254114',
 'MLB41236874',
 'MLB48088563',
 'MLB48294410',
 'MLB48167643',
 'MLB48913705',
 'MLB25212635',
 'MLB27545778',
 'MLB27049620',
 'MLB28371081',
 'MLB39049325',
 'MLB27552958',
 'MLB30153156',
 'MLB28650588',
 'MLB28027552',
 'MLB34280639',
 'MLB32452188',
 'MLB57493542',
 'MLB27923664',
 'MLB37814273',
 'MLB49851124',
 'MLB51913658',
 'MLB29456447',
 'MLB29099491',
 'MLB32595992',
 'MLB54900862',
 'MLB61796963',
 'MLB27505333',
 'MLB28942822',
 'MLB61678134',
 'MLB33951054',
 'MLB59553253',
 'MLB40684093',
 'MLB49983264',
 'MLB45327421',
 'MLB27632861',
 'MLB29462846',
 'MLB61658188',
 'MLB60365723',
 'MLB27536473',
 'MLB61981524',
 'MLB36274614',
 'MLB44856922',
 'MLB46275843',
 'MLB42751333',
 'MLB27753509',
 'MLB27696759',
 'MLB61118503',
 'MLB34811390',
 'MLB23883954',
 'MLB61334901',
 'MLB61335802',
 'MLB36757007',
 'MLB60530453',
 'MLB37337301',
 'MLB60285699',
 'MLB42484214',
 'MLB47590308',
 'MLB29017989',
 'MLB29629811',
 'MLB61591641',
 'MLB61982918',
 'MLB59579916',
 'MLB25804187',
 'MLB36505335',
 'MLB27716996',
 'MLB32392962',
 'MLB54211500',
 'MLB27070882',
 'MLB35952056',
 'MLB27791831',
 'MLB25345189',
 'MLB27070881',
 'MLB36070069',
 'MLB52141265',
 'MLB59684762',
 'MLB27751836',
 'MLB27631605',
 'MLB44994733',
 'MLB60238801',
 'MLB42420814',
 'MLB40679937',
 'MLB40654542',
 'MLB24795182',
 'MLB23903660',
 'MLB42982122',
 'MLB40680370',
 'MLB45873172',
 'MLB28954607',
 'MLB54262188',
 'MLB42739681',
 'MLB35513817',
 'MLB48524616',
 'MLB59652336',
 'MLB37649671',
 'MLB42808189',
 'MLB26889701',
 'MLB36044733',
 'MLB25527027',
 'MLB28933460',
 'MLB25632565',
 'MLB26889737',
 'MLB40686404',
 'MLB29710794',
 'MLB27643223',
 'MLB27495545',
 'MLB47653355',
 'MLB29371634',
 'MLB61340046',
 'MLB24601884',
 'MLB41100765',
 'MLB27526925',
 'MLB54970860',
 'MLB48917284',
 'MLB35986262',
 'MLB26889740',
 'MLB42556355',
 'MLB27227783',
 'MLB31765781',
 'MLB27782635',
 'MLB35581376',
 'MLB40060774',
 'MLB25345202',
 'MLB36144866',
 'MLB25804192',
 'MLB36538021',
 'MLB32819327',
 'MLB56433108',
 'MLB23871295',
 'MLB52845665',
 'MLB35530004',
 'MLB25527062',
 'MLB25527080',
 'MLB32688329',
 'MLB25804191',
 'MLB26375094',
 'MLB24694027',
 'MLB60853607',
 'MLB29643573',
 'MLB53617829',
 'MLB29464725',
 'MLB44203495',
 'MLB53049225',
 'MLB32440756',
 'MLB37143172',
 'MLB36381597',
 'MLB28628160',
 'MLB29359017',
 'MLB38566655',
 'MLB25527074',
 'MLB35447011',
 'MLB32449044',
 'MLB28443634',
 'MLB25794475',
 'MLB32448295',
 'MLB26889689',
 'MLB57569985',
 'MLB44870991',
 'MLB32032566',
 'MLB52863331',
 'MLB28981287',
 'MLB36357719',
 'MLB41302832',
 'MLB34035464',
 'MLB56639217',
 'MLB44977542',
 'MLB35910960',
 'MLB34591276',
 'MLB45776894',
 'MLB43495558',
 'MLB49706219',
 'MLB45794549',
 'MLB52888596',
 'MLB28946589',
 'MLB39385584',
 'MLB41822818',
 'MLB44275206',
 'MLB32627076',
 'MLB42556459',
 'MLB25716378',
 'MLB39445684',
 'MLB42734954',
 'MLB26889727',
 'MLB34137095',
 'MLB41100893',
 'MLB32381654',
 'MLB61266052',
 'MLB34853793',
 'MLB62173818',
 'MLB61444679',
 'MLB47065738',
 'MLB27708699',
 'MLB42443229',
 'MLB46159986',
 'MLB42686657',
 'MLB40759619',
 'MLB29520407',
 'MLB21925155',
 'MLB24971238',
 'MLB35412503',
 'MLB25655635',
 'MLB35336149',
 'MLB49405920',
 'MLB46662995',
 'MLB28930016',
 'MLB21718682',
 'MLB21446708',
 'MLB41996280',
 'MLB21604324',
 'MLB43507913',
 'MLB28927417',
 'MLB45687523',
 'MLB28751058',
 'MLB24971334',
 'MLB34132099',
 'MLB42151478',
 'MLB33961390',
 'MLB23836524',
 'MLB45932804',
 'MLB46002487',
 'MLB56407149',
 'MLB25369510',
 'MLB52866256',
 'MLB34810942',
 'MLB23439133',
 'MLB21885251',
 'MLB23300175',
 'MLB44147369',
 'MLB21477902',
 'MLB21642585',
 'MLB33368771',
 'MLB54343629',
 'MLB57303578',
 'MLB21695241',
 'MLB48705460',
 'MLB23858289',
 'MLB25069431',
 'MLB22237987',
 'MLB39931956',
 'MLB42189569',
 'MLB30329321',
 'MLB21958187',
 'MLB45295319',
 'MLB61760126',
 'MLB22707667',
 'MLB25556226',
 'MLB21478051',
 'MLB34258560',
 'MLB23553113',
 'MLB24282666',
 'MLB23424369',
 'MLB21703284',
 'MLB21876634',
 'MLB25969744',
 'MLB21870150',
 'MLB44849635',
 'MLB21714688',
 'MLB22856122',
 'MLB21464332',
 'MLB53397197',
 'MLB61271037',
 'MLB24873399',
 'MLB35430763',
 'MLB25719970',
 'MLB21775769',
 'MLB41432353',
 'MLB48444560',
 'MLB21604140',
 'MLB23424292',
 'MLB39032970',
 'MLB62182513',
 'MLB21483208',
 'MLB21720857',
 'MLB41521714',
 'MLB21792068',
 'MLB22128247',
 'MLB22382016',
 'MLB23162942',
 'MLB21477996',
 'MLB21303129',
 'MLB21293520',
 'MLB38009719',
 'MLB45331586',
 'MLB52125317',
 'MLB35228362',
 'MLB51398858',
 'MLB21695188',
 'MLB51865504',
 'MLB21368789',
 'MLB36648513',
 'MLB44018106',
 'MLB25880382',
 'MLB50493660',
 'MLB42955042',
 'MLB43506427',
 'MLB35602964',
 'MLB21865322',
 'MLB21847579',
 'MLB21478080',
 'MLB21641868',
 'MLB22688696',
 'MLB51923248',
 'MLB35508718',
 'MLB42175520',
 'MLB48718657',
 'MLB21510515',
 'MLB36853147',
 'MLB59173373',
 'MLB25397031',
 'MLB21293417',
 'MLB39432090',
 'MLB40160069',
 'MLB39104101',
 'MLB40231494',
 'MLB39059328',
 'MLB21482456',
 'MLB22897252',
 'MLB49750655',
 'MLB45706954',
 'MLB21293972',
 'MLB37928308',
 'MLB39009716',
 'MLB43014319',
 'MLB46350683',
 'MLB57773424',
 'MLB53973818',
 'MLB40118409',
 'MLB58045811',
 'MLB21451786',
 'MLB23021348',
 'MLB42110382',
 'MLB29009946',
 'MLB23555531',
 'MLB26790075',
 'MLB22793767',
 'MLB23021352',
 'MLB50852344',
 'MLB40153580',
 'MLB22856084',
 'MLB21635772',
 'MLB25069552',
 'MLB33974217',
 'MLB35059181',
 'MLB25564743',
 'MLB21393519',
 'MLB37252265',
 'MLB21668005',
 'MLB21604255',
 'MLB28939341',
 'MLB21695244',
 'MLB43689484',
 'MLB22876355',
 'MLB41830188',
 'MLB23619763',
 'MLB23000148',
 'MLB21303130',
 'MLB39244617',
 'MLB36362741',
 'MLB37989131',
 'MLB25457121',
 'MLB23661952',
 'MLB21312681',
 'MLB37033511',
 'MLB46671831',
 'MLB21673573',
 'MLB21838424',
 'MLB21948697',
 'MLB34705107',
 'MLB35369173',
 'MLB22794852',
 'MLB21884211',
 'MLB35563269',
 'MLB38063449',
 'MLB21798890',
 'MLB21293131',
 'MLB24520922',
 'MLB61750853',
 'MLB35517817',
 'MLB52857680',
 'MLB35577210',
 'MLB36050923',
 ...]

In [8]:
len(smartObjectsID)

5093

In [ ]:
smartObjectsReviews = ( avaliacoes[avaliacoes["id"].isin(smartObjectsID)]
                       .drop_duplicates()
                       .reset_index(drop=True)
                       .dropna() )
smartObjectsReviews.to_csv('../data/smart_objects/smart_objects_reviews.csv', index=False)

In [10]:
smartObjectsReviews['nota'].value_counts()

nota
5       2757
4        236
1         55
3         29
2         15
out.       1
mar.       1
Name: count, dtype: int64

In [ ]:
smartObjectsQuestions = (perguntas[perguntas["id"].isin(smartObjectsID)]
                         .drop_duplicates()
                         .reset_index(drop=True))
smartObjectsQuestions.to_csv('../data/smart_objects/smart_objects_questions.csv', index=False)

In [27]:
smartObjects = produtos[produtos["id"].isin(smartObjectsID)].drop_duplicates().reset_index(drop=True) 
smartObjects.to_csv('../data/smart_objects/smart_objects_products.csv', index=False)

In [13]:
smartObjects['domain_id'].value_counts()[:25]

domain_id
MLB-SMART_SPEAKERS                     626
MLB-SMARTWATCHES                       474
MLB-LIGHT_BULBS                        415
MLB-HOME_ALARMS_AND_SENSORS            375
MLB-TELEVISIONS                        359
MLB-DIMMERS                            293
MLB-CELLPHONES                         279
MLB-ELECTRIC_LOCKS                     275
MLB-NOTEBOOKS                          273
MLB-SURVEILLANCE_CAMERAS               258
MLB-ELECTRICAL_OUTLETS                 217
MLB-WALL_LIGHT_SWITCHES                191
MLB-DRONES                             146
MLB-MICROPHONES                        145
MLB-PROJECTORS                         140
MLB-VR_HEADSETS                        107
MLB-HEADPHONES                         105
MLB-PRINTERS                            97
MLB-ELECTRIC_SCOOTERS                   83
MLB-IRRIGATION_TIMERS                   50
MLB-FANS                                44
MLB-BLOOD_GLUCOSE_METERS                39
MLB-DIGITAL_TEMPERATURE_CONTROLLERS     36
MLB-AIR_CONDITIONERS                    33
MLB-ELECTRIC_HOME_HEATERS               14
Name: count, dtype: int64

In [28]:
smartObjectsContexts = contextos[contextos["id"].isin(smartObjectsID)].drop_duplicates().reset_index(drop=True) 
smartObjectsContexts.to_csv('../data/smart_objects/smart_objects_contexts.csv', index=False)

In [15]:
smartObjectsContexts['Context_Id'].value_counts()[:25]

Context_Id
BRAND                         5085
MODEL                         4851
COLOR                         3548
WITH_BLUETOOTH                2653
WITH_WI_FI                    2362
LINE                          2274
HEIGHT                        1949
WEIGHT                        1770
WIDTH                         1713
MAIN_COLOR                    1558
DISPLAY_SIZE                  1385
VOLTAGE                       1221
MANUFACTURER                  1118
DEPTH                         1062
WITH_WIFI                      938
DISPLAY_TYPE                   918
UNITS_PER_PACK                 901
ACCESSORIES_INCLUDED           867
POWER                          764
MATERIAL                       737
COMPATIBLE_SMART_APPS          733
ANATEL_HOMOLOGATION_NUMBER     730
SALE_FORMAT                    728
WITH_GPS                       724
BATTERY_CAPACITY               724
Name: count, dtype: int64

In [16]:
smartObjectsContexts["Context_Id"].value_counts()[:25]

Context_Id
BRAND                         5085
MODEL                         4851
COLOR                         3548
WITH_BLUETOOTH                2653
WITH_WI_FI                    2362
LINE                          2274
HEIGHT                        1949
WEIGHT                        1770
WIDTH                         1713
MAIN_COLOR                    1558
DISPLAY_SIZE                  1385
VOLTAGE                       1221
MANUFACTURER                  1118
DEPTH                         1062
WITH_WIFI                      938
DISPLAY_TYPE                   918
UNITS_PER_PACK                 901
ACCESSORIES_INCLUDED           867
POWER                          764
MATERIAL                       737
COMPATIBLE_SMART_APPS          733
ANATEL_HOMOLOGATION_NUMBER     730
SALE_FORMAT                    728
WITH_GPS                       724
BATTERY_CAPACITY               724
Name: count, dtype: int64

In [17]:
speakers = produtos[produtos['domain_id']=="MLB-ELECTRIC_HOME_HEATERS"]
idspeaker = speakers["id"].tolist()

contextos[contextos["id"].isin(idspeaker)]["Context_Id"].value_counts()[:90]

Context_Id
BRAND                          300
MODEL                          294
COLOR                          235
ELECTRIC_HEATER_TYPE           206
HEATER_MAX_POWER               192
MAIN_COLOR                     172
WIDTH                          157
WITH_FAN_MODE                  156
WITH_OSCILLATION               156
HEIGHT                         154
WITH_OVERHEAT_PROTECTION       153
LENGTH                         148
WITH_TURBO_FUNCTION            132
WITH_THERMOSTAT                114
LINE                           113
VOLTAGE                        110
WITH_REMOTE_CONTROL             85
MATERIAL                        81
WITH_TIMER                      63
WITH_TRANSPORT_SLOT             61
WITH_TEMPERATURE_SELECTOR       59
ALPHANUMERIC_MODEL              56
WITH_AUTO_SHUT_OFF              55
WITH_WI_FI                      46
WITH_OVERVOLTAGE_PROTECTION     44
ENERGY_EFFICIENCY               32
POWER_LEVELS_NUMBER             30
MANUFACTURER                    21
DETAILED_MODEL                  21
HEATING_AREA                    21
MPN                              2
Name: count, dtype: int64

In [18]:
smartObjects

,id,date_created,catalog_product_id,domain_id,name,main_features,quality_type,priority,type,keywords,description
0,MLB36333923,2024-04-30T07:10:59Z,MLB36333923,MLB-REFRIGERATORS,Geladeira Portátil Automotiva Cfx335 E,[],COMPLETE,MEDIUM,PRODUCT,Geladeira Portátil Automotiva Cfx335 E,NaN
1,MLB36139109,2024-04-24T00:05:50Z,MLB36139109,MLB-REFRIGERATORS,Geladeira Portátil Automotiva Cfx345 12v/24v,[],COMPLETE,MEDIUM,PRODUCT,Geladeira Portátil Automotiva Cfx345 12v/24v,NaN
2,MLB21345002,2023-01-25T11:36:55Z,MLB21345002,MLB-REFRIGERATORS,Geladeira LG LS66sdp No Frost 617lt,[],COMPLETE,MEDIUM,PRODUCT,Geladeira LG LS66sdp No Frost 617lt,NaN
3,MLB38703841,2024-07-29T00:19:00Z,MLB38703841,MLB-REFRIGERATORS,Geladeira Duplex Inverse Evolution Smartthings...,[],COMPLETE,MEDIUM,PRODUCT,Geladeira Duplex Inverse Evolution Smartthings...,NaN
4,MLB36398531,2024-04-30T22:21:23Z,MLB36398531,MLB-REFRIGERATORS,Geladeira Inverter Auto Defrost LG Freezer 451l,[],COMPLETE,MEDIUM,PRODUCT,Geladeira Inverter Auto Defrost LG Freezer 451l,NaN
...,...,...,...,...,...,...,...,...,...,...,...
5088,MLB38765729,2024-07-31T01:39:07Z,MLB38765729,MLB-DIMMERS,Interruptor inteligente Wi-Fi para ventilador ...,[],COMPLETE,MEDIUM,PRODUCT,Interruptor inteligente Wi-Fi para ventilador ...,NaN
5089,MLB45805005,2025-01-30T19:51:00Z,MLB45805005,MLB-DIMMERS,Interruptor Inteligente Zigbee Novadigital 2 T...,[],COMPLETE,MEDIUM,PRODUCT,Interruptor Inteligente Zigbee Novadigital 2 T...,NaN
5090,MLB47688342,2025-04-04T17:32:34Z,MLB47688342,MLB-DIMMERS,Interruptor Inteligente Zigbee Novadigital 1 T...,[],COMPLETE,MEDIUM,PRODUCT,Interruptor Inteligente Zigbee Novadigital 1 T...,NaN
5091,MLB39454456,2024-08-22T19:56:27Z,MLB39454456,MLB-DIMMERS,Interruptor Inteligente Wi-fi Com Função Dimme...,[],COMPLETE,MEDIUM,PRODUCT,Interruptor Inteligente Wi-fi Com Função Dimme...,NaN
5092,MLB44773654,2024-12-14T01:35:19Z,MLB44773654,MLB-DIMMERS,Interruptor Inteligente Zigbee 4x4 4 Teclas Fí...,[],COMPLETE,MEDIUM,PRODUCT,Interruptor Inteligente Zigbee 4x4 4 Teclas Fí...,NaN

# Gráfico de % pos neg

In [24]:
# função de remoção de stopwords
def removerstopwords(texto):
    # deixando texto em minúsculo
    texto = texto.lower()

    # removendo pontuações do texto
    pontuacao = str.maketrans('', '', string.punctuation)
    texto = texto.translate(pontuacao)

    # removendo stopwords do texto
    palavras = word_tokenize(texto, language='portuguese')
    stopwaords = set(stopwords.words('portuguese'))
    palavrasfiltradas = [palavra for palavra in palavras if palavra.lower() not in stopwaords]

    # removendo espaços vazios restantes dos tokens
    listasemvazios = list(filter(None, palavrasfiltradas))

    return listasemvazios

def analisesentimentosBlob(texto):
  # Cria o objeto TextBlob
  blob = TextBlob(texto)

  # Pega o sentimento
  # se > 0.1 é positivo, se 0 é neutro e se < -0.1 é negativo
  sentimento = blob.sentiment
  return sentimento.polarity

def analisesentimentosLeIA(texto):
  # Cria o objeto LeIA
  s = SentimentIntensityAnalyzer()


  # Pega o sentimento
  # se > 0.05 é positivo, entre é neutro e se < -0.05 é negativo
  sentimento = s.polarity_scores(texto)
  return sentimento["compound"]

def tiposentimento(x):
  if x > 0.05:
    return 'Positivo'
  if x < -0.05:
    return 'Negativo'
  else:
    return 'Neutro'

def calcula_porcentagem_sentimento(df:pd.DataFrame)->dict:
    res = dict()
    for domain in df['domain_id'].unique():
        df_domain = df[df['domain_id'] == domain]
        pos = df_domain[df_domain['tiposentimento'] == 'Positivo']
        neg = df_domain[df_domain['tiposentimento'] == 'Negativo']
        tot = len(pos)+len(neg)
        res[domain] = {'pos': len(pos)/tot, "neg": len(neg)/tot}
        # res[domain] = {'pos': len(pos), "neg": len(neg)}
    return res

In [29]:
smartObjectsReviews['sentimento'] = smartObjectsReviews['texto'].apply(analisesentimentosLeIA)
smartObjectsReviews['tiposentimento'] = smartObjectsReviews['sentimento'].apply(tiposentimento)
smartObjectsReviews = pd.merge(smartObjectsReviews, smartObjects[['id', 'domain_id']], on='id', how='left').reset_index(drop=True)
smartObjectsReviews.to_csv('../data/smart_objects/smart_objects_reviews.csv', index=False)

In [30]:
smartObjectsQuestions['sentimento_pergunta'] = smartObjectsQuestions['pergunta'].apply(analisesentimentosLeIA)
smartObjectsQuestions['tiposentimento_pergunta'] = smartObjectsQuestions['sentimento_pergunta'].apply(tiposentimento)
smartObjectsQuestions = pd.merge(smartObjectsQuestions, smartObjects[['id', 'domain_id']], on='id', how='left').reset_index(drop=True)

smartObjectsQuestions['sentimento_resposta'] = smartObjectsQuestions['resposta'].apply(analisesentimentosLeIA)
smartObjectsQuestions['tiposentimento_resposta'] = smartObjectsQuestions['sentimento_resposta'].apply(tiposentimento)
smartObjectsQuestions = pd.merge(smartObjectsQuestions, smartObjects[['id', 'domain_id']], on='id', how='left').reset_index(drop=True)


smartObjectsQuestions.to_csv('../data/smart_objects/smart_objects_questions.csv', index=False)

In [25]:
percentual = calcula_porcentagem_sentimento(smartObjectsReviews)
percentual

{'MLB-REFRIGERATORS': {'pos': 1.0, 'neg': 0.0},
 'MLB-FANS': {'pos': 1.0, 'neg': 0.0},
 'MLB-DIGITAL_TEMPERATURE_CONTROLLERS': {'pos': 0.7142857142857143,
  'neg': 0.2857142857142857},
 'MLB-ELECTRICAL_OUTLETS': {'pos': 0.9201388888888888,
  'neg': 0.0798611111111111},
 'MLB-SMARTWATCHES': {'pos': 0.9085365853658537, 'neg': 0.09146341463414634},
 'MLB-VR_HEADSETS': {'pos': 0.7272727272727273, 'neg': 0.2727272727272727},
 'MLB-BLOOD_GLUCOSE_METERS': {'pos': 0.896551724137931,
  'neg': 0.10344827586206896},
 'MLB-HEADPHONES': {'pos': 0.9375, 'neg': 0.0625},
 'MLB-MICROPHONES': {'pos': 0.9324324324324325, 'neg': 0.06756756756756757},
 'MLB-HOME_ALARMS_AND_SENSORS': {'pos': 0.8805970149253731,
  'neg': 0.11940298507462686},
 'MLB-TELEVISIONS': {'pos': 0.9182389937106918, 'neg': 0.08176100628930817},
 'MLB-PROJECTORS': {'pos': 0.8076923076923077, 'neg': 0.19230769230769232},
 'MLB-ELECTRIC_SCOOTERS': {'pos': 1.0, 'neg': 0.0},
 'MLB-WALL_LIGHT_SWITCHES': {'pos': 0.9295774647887324,
  'neg': 0.07042253521126761},
 'MLB-SMART_SPEAKERS': {'pos': 0.8817891373801917, 'neg': 0.1182108626198083},
 'MLB-DIMMERS': {'pos': 0.9202898550724637, 'neg': 0.07971014492753623},
 'MLB-LIGHT_BULBS': {'pos': 0.9383561643835616, 'neg': 0.06164383561643835},
 'MLB-NOTEBOOKS': {'pos': 0.8098591549295775, 'neg': 0.19014084507042253},
 'MLB-CELLPHONES': {'pos': 0.9027777777777778, 'neg': 0.09722222222222222},
 'MLB-DRONES': {'pos': 0.7321428571428571, 'neg': 0.26785714285714285},
 'MLB-PRINTERS': {'pos': 0.8648648648648649, 'neg': 0.13513513513513514},
 'MLB-ELECTRIC_LOCKS': {'pos': 0.85, 'neg': 0.15},
 'MLB-SURVEILLANCE_CAMERAS': {'pos': 0.9216589861751152,
  'neg': 0.07834101382488479}}